
ignore:
  - "/Applications"
  - "/usr"
  - "example"
  - "tests"
  - "test/lib/catch.hpp"

fixes:
  - "src/libmemcachedinternal::src/libmemcached"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
  range: 50..80
  round: nearest
  precision: 0
