set(LIBMEMCACHED_WITH_SASL_SUPPORT 0)

set(HAVE_FNV64_HASH 1)
set(HAVE_MURMUR_HASH 1)
set(HAVE_HSIEH_HASH 0)

set(HAVE_DTRACE 0)
set(HAVE_VISIBILITY 1)
set(HAVE_GCC_BUILTIN_ATOMIC 1)
set(HAVE_SHARED_ENABLED 1)
