Found key pid
Found key uptime
Found key time
Found key version
Found key pointer_size
Found key rusage_user
Found key rusage_system
Found key rusage_user_seconds
Found key rusage_user_microseconds
Found key rusage_system_seconds
Found key rusage_system_microseconds
Found key curr_items
Found key total_items
Found key bytes
Found key curr_connections
Found key total_connections
Found key connection_structures
Found key cmd_get
Found key cmd_set
Found key get_hits
Found key get_misses
Found key evictions
Found key bytes_read
Found key bytes_written
Found key limit_maxbytes
Found key threads
