=head1 NAME

memstat - Display the operating status of a single or group of memcached servers

=head1 SYNOPSIS

memstat [options]

=head1 DESCRIPTION

memstat dumps the state of memcached servers. It displays all data to
stdout.

You can specify servers via the --servers option or memcat will use the
environmental variable MEMCACHED_SERVERS.

For a full list of its operations run the tool with the --help option.

=head1 HOME

To find out more information please check: http://tangent.org/552/libmemcached.html

=head1 AUTHOR

Brian Aker, brian@tangent.org

=head1 SEE ALSO

memcached(1) libmemcached(3)

=cut

