include(EnableDtrace)
if(ENABLE_DTRACE)
    find_package(DTrace)
    if(DTRACE_EXECUTABLE)
        configure_set(HAVE_DTRACE 1)
    else()
        message(WARNING "The dtrace command is required to enable dtrace/systemtap support.")
    endif()
endif()
